#!/bin/sh

run() {
	job="$(date +"%M") $(($(date +"%H")+1)) * * * $(which $0) -k"
	/opt/bitwarden &
	echo $! > /tmp/bitwarden-wrapper.pid
	(crontab -l; echo "$job") | crontab -
}

kil() {
	kill $(cat /tmp/bitwarden-wrapper.pid)
	crontab -l | sed -e '/bitwarden -k/d' | crontab -
}

case "$1" in
	-k) kil;;
	*) run;;
esac

exit 0
