#!/bin/sh
# Required packages: wget

# Purge existing package install
apt purge firefox-esr "firefox-esr*" -qqy > /dev/null

# System wide install
cd /opt

# Download the latest 64bit Firefox build
[ -f firefox.tar.gz ] && rm firefox.tar.gz
wget "https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=fr" -O firefox.tar.gz

# Backup the existing install (if any) and delete the previous backup (if any)
if [ -d firefox ]; then
  if [ -d firefox.old ]; then
    rm -rf firefox.old
  fi
  cp -r firefox firefox.old
fi

# Extract the downloaded build
tar xvf firefox.tar.gz

# Linking to /usr/bin/firefox for ease of use
[ -L /usr/bin/firefox ] && rm /usr/bin/firefox
ln -s /opt/firefox/firefox /usr/bin/firefox

# Setting Firefox as an application (needed below for MIME types)
echo "[Desktop Entry]
Name=Firefox Stable
Comment=Web Browser
Exec=/opt/firefox/firefox %u
Terminal=false
Type=Application
Icon=/opt/firefox/browser/chrome/icons/default/default128.png
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;
StartupNotify=true" > /usr/share/applications/firefox-stable.desktop

# Setting Firefox as default browser
update-alternatives --install /usr/bin/x-www-browser x-www-browser /opt/firefox/firefox 1000
update-alternatives --install /usr/bin/gnome-www-browser gnome-www-browser /opt/firefox/firefox 1000
update-alternatives --set x-www-browser /opt/firefox/firefox
update-alternatives --set gnome-www-browser /opt/firefox/firefox

# Updating MIME types and XDG
update-mime
grep "firefox" /etc/mailcap | cut -d ';' -f 1 | while read i; do
  xdg-mime default /usr/share/applications/firefox-stable.desktop $i
done

exit 0
