#!/bin/sh

# Controls ncmpcpp or spotify depending on which is running (using ncmpcppctl and spotifyctl scripts)

ncmpcpp=0
spotify=0

# Is ncmpcpp running ?
if pgrep ncmpcpp > /dev/null
then
	ncmpcpp=1
fi

# Is spotify running ?
if pgrep spotify > /dev/null
then
	spotify=1
fi

# If only ncmpcpp is running, use ncmpcppctl
if [ "$ncmpcpp" -eq "1" -a "$spotify" -ne "1" ]
then
	cmd="ncmpcppctl"
# Else if only Spotify is running, use spotifyctl
elif [ "$spotify" -eq "1" -a "$ncmpcpp" -ne "1" ]
then
	cmd="spotifyctl"
# Else, if both are running, ncmpcppctl prevails
else
	cmd="ncmpcppctl"
fi

# Pass command line argument to either ncmpcppctl or spotifyctl
eval "$cmd $1"

exit 0
