#!/bin/sh

# Wrapper for ncmpcpp, allowing --current-song="format" command (from newer release) on 0.5

for arg in "$@"
do
	if [ "$(echo $arg | cut -d '=' -f 1)" = "--current-song" ]
	then
		arg="--now-playing '$(echo $arg | cut -d '=' -f 2)'"
	fi
	argstr="$argstr $arg"
done

eval "ncmpcpp.real $argstr"

exit 0
