#!/bin/sh

# Displays terminal colors

echo "\033[40m                \033[100m                \033[0m"
echo "\033[41m                \033[101m                \033[0m"
echo "\033[42m                \033[102m                \033[0m"
echo "\033[43m                \033[103m                \033[0m"
echo "\033[44m                \033[104m                \033[0m"
echo "\033[45m                \033[105m                \033[0m"
echo "\033[46m                \033[106m                \033[0m"
echo "\033[47m                \033[107m                \033[0m"

exit 0
